#!/bin/sh
export RED='\033[0;31m' GREEN='\033[0;32m' YELLOW='\033[1;33m' LIGHT_BLUE='\033[1;34m' DEFAULT='\033[0m'
export PRI_A=$YELLOW PRI_B=$GREEN PRI_C=$LIGHT_BLUE EXPIRED=$RED
today=$(date -d "0" +%s)
out () {
	projects=$(echo "$line" | grep -o '\+\w\+' | tr '\n' ' ' | sed 's/ $//')
	contexts=$(echo "$line" | grep -o '@\w\+' | tr '\n' ' ' | sed 's/ $//')
	priority=$(echo "$line" | grep -o '^([A-Z])')
	p=$(echo "$priority"  | sed 's/(//;s/)//')
	[ -z "$priority" ] && priority="ZZZZZ"
	pinned=$(echo "$line" | grep -Po '(?:\([A-Z]\) )?!' | sed 's/\((\w\+)\)\? \?//;s/!/📌/')
	due=$(echo "$line" | grep -Po 'due:\d{4}-\d{2}-\d{2}' | sed 's/due://')
	taskdate=$(date -d "$due" +%s)
	[ -z "$due" ] && due="9999-99-99"
	task=$(echo "$line" | sed 's/due:\([0-9]\{4\}\)-\([0-9]\{2\}\)-\([0-9]\{2\}\) \?//;s/\((\w\+)\)\? \?!\? \?//;s/\(+\w\+\) \?//g;s/\(@\w\+\) \?//g' )
	[ $p ] && c="PRI_$p"
	if [ $today -gt $taskdate ] ; then
		c="EXPIRED"
	fi
	[ $c ] && eval color=\$$c
	echo -e "${color} |$pinned|$priority|$task|$contexts|$projects|$due${DEFAULT}" | sed 's/[[:blank:]]\+/ /g'
	unset projects contexts priority pinned due task color c p taskdate
}
	search=$(echo "$@" | sed 's/ /\\|/g')
	while IFS= read -r line ; do
		out &
	done < $HOME/todo.txt | sort -t'|' -k2r,2 -k7,7 -k3,3 | sed 's/|//' |  column -t -o'|' -s'|' | tr '|' '\t' | sed 's/9999-99-99//;s/ZZZZZ//' | grep -i "${search:-^}"
